Updated Links H4 and fix typo
JJ/CC pull request #113
Opened 2022-08-23 09:37 UTC by e89835

Updated links for Circle CI, and updated Shippable link to JFrog (https://jfrog.com/blog/weve-acquired-shippable-to-complete-devops-pipeline-automation-from-code-to-production/). Fixed minor typographical error.

2022-08-23 09:40 UTC, e89835 commented
Same error as Pull #112 , Lint Markdown error in `1. Infraestructura.md` line 128: line length.

2022-08-23 09:51 UTC, JJ requested changes
Ya que se hace un cambio, prefiero que se elimine, si no te importa.

2022-08-23 09:51 UTC, JJ commented on documentos/proyecto/4.CI.md
> +  [Travis](https://travis-ci.com), [JFrog](https://jfrog.com/) (que incorpora
Realmente aquí preferiría eliminar Travis. JFrog tampoco es un sistema de integración continua, y creo que lo que sustituye a shippable ya no es gratuito.

2022-08-23 10:02 UTC, e89835 commented on documentos/proyecto/4.CI.md
> +  [Travis](https://travis-ci.com), [JFrog](https://jfrog.com/) (que incorpora
Vale, entonces elimino Travis y JFrog. ¿Añado alguno o dejo sólo Circle CI?

2022-08-23 11:53 UTC, JJ commented on documentos/proyecto/4.CI.md
> +  [Travis](https://travis-ci.com), [JFrog](https://jfrog.com/) (que incorpora
Github actions, por ejemplo.

2022-08-25 09:31 UTC, JJ approved these changes
Thanks!

2022-08-26 08:08 UTC, merged